on:
  push:
    tags:
      - "*"

name: Split
jobs:
  tag:
    runs-on: ubuntu-20.04
    steps:
      - name: "split"
        id: split
        uses: tanaphonble/tag-splitter-action@v0.0.4
      - name: "set env"
        run: echo "Name=${{steps.split.outputs.name}} Version=${{steps.split.outputs.version}}"
