on:
  push:
    tags:
      - "*"

name: Split
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "split"
        id: split
        uses: tanaphonble/tag-splitter-action@v0.0.1
      - name: "set env"
        run: echo "Name=${{steps.tag.outputs.split.name}} Version=${{steps.tag.outputs.split.name}}"
